name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
#  build_wheels:
#    name: Build wheels on ubuntu-20.04
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      # Used to host cibuildwheel
#      - uses: actions/setup-python@v2
#
#      - name: Install cibuildwheel
#        run: python3 -m pip install cibuildwheel==2.0.0a2
#      - name: Build wheels
#        run: python3 -m cibuildwheel --output-dir wheelhouse
#        # to supply options, put them in 'env', like:
#        env:
#          CIBW_BEFORE_ALL: yum install -y  lapack-devel  blas-devel
#
#      - uses: actions/upload-artifact@v2
#        with:
#          path: ./wheelhouse/*.whl
  
  build_wheels_mac:
    name: Build wheels on mac
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.0.0a2
      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_ALL: brew install openblas python
          CIBW_ARCHS_MACOS: x86_64 universal2
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheel_win:
    name: Build Wheel on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-activate-base: false  # Do not auto-activate base environment
          python-version: '3.11'

      - name: Configure Conda
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict

      - name: Create Conda Environment and Install Dependencies
        run: |
          conda create -n build-env -y python=3.11 cmake blas=*=openblas lapack numpy setuptools wheel
          conda run -n build-env python -m pip install cibuildwheel

      - name: Build the Wheel
        run: |
          conda run -n build-env python -m cibuildwheel --platform windows --output-dir wheelhouse

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheel
          path: wheelhouse/*.whl
