name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
#  build_wheels:
#    name: Build wheels on ubuntu-20.04
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      # Used to host cibuildwheel
#      - uses: actions/setup-python@v2
#
#      - name: Install cibuildwheel
#        run: python3 -m pip install cibuildwheel==2.0.0a2
#      - name: Build wheels
#        run: python3 -m cibuildwheel --output-dir wheelhouse
#        # to supply options, put them in 'env', like:
#        env:
#          CIBW_BEFORE_ALL: yum install -y  lapack-devel  blas-devel
#
#      - uses: actions/upload-artifact@v2
#        with:
#          path: ./wheelhouse/*.whl
  
  build_wheels_mac:
    name: Build wheels on mac
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.0.0a2
      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_ALL: brew install openblas python
          CIBW_ARCHS_MACOS: x86_64 universal2
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheel_win:
    name: Build Wheel on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the code

    - name: Install Miniconda
      run: |
        choco install miniconda3 --yes  # Install Miniconda using Chocolatey
        echo "C:\\tools\\miniconda3" >> $GITHUB_PATH  # Add Miniconda to PATH

    - name: Configure Conda
      run: |
        source C:/tools/miniconda3/etc/profile.d/conda.sh  # Source Conda script
        conda init bash  # Initialize Conda for bash shell
        conda config --add channels conda-forge  # Add conda-forge channel
        conda config --set channel_priority strict  # Prioritize conda-forge

    - name: Create Conda Environment
      shell: bash
      run: |
        source C:/tools/miniconda3/etc/profile.d/conda.sh  # Source Conda script
        conda create -n build-env -y python=3.11 cmake blas=*=openblas lapack numpy setuptools wheel  # Create environment
        conda activate build-env  # Activate environment
        python -m pip install cibuildwheel  # Install cibuildwheel for building wheels

    - name: Build the Wheel
      shell: bash
      run: |
        source C:/tools/miniconda3/etc/profile.d/conda.sh  # Source Conda script
        conda activate build-env  # Activate environment
        python -m cibuildwheel --platform windows --output-dir wheelhouse  # Build wheels and save them to 'wheelhouse'

    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-wheel
        path: wheelhouse/*.whl  # Upload the built wheels
