name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
#  build_wheels:
#    name: Build wheels on ubuntu-20.04
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      # Used to host cibuildwheel
#      - uses: actions/setup-python@v2
#
#      - name: Install cibuildwheel
#        run: python3 -m pip install cibuildwheel==2.0.0a2
#      - name: Build wheels
#        run: python3 -m cibuildwheel --output-dir wheelhouse
#        # to supply options, put them in 'env', like:
#        env:
#          CIBW_BEFORE_ALL: yum install -y  lapack-devel  blas-devel
#
#      - uses: actions/upload-artifact@v2
#        with:
#          path: ./wheelhouse/*.whl
  
  build_wheels_mac:
    name: Build wheels on mac
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.0.0a2
      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_ALL: brew install openblas python
          CIBW_ARCHS_MACOS: x86_64 universal2
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_wheel_win:
    name: Build Wheel on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Miniconda and create environment
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-activate-base: true
          python-version: '3.11'
          channels: conda-forge
          channel-priority: strict

      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      # Install dependencies and tools (LAPACK, BLAS, etc.)
      - name: Install dependencies
        run: |
          conda install -y -c conda-forge libblas liblapack openblas numpy setuptools wheel
          python -m pip install cibuildwheel

      # Set up C/C++ compiler (MSVC on Windows)
      - name: Set up C/C++ compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest

      # Build the Wheel using cibuildwheel
      - name: Build the Wheel
        run: |
          python -m cibuildwheel --platform windows --output-dir wheelhouse

      # Upload the built wheel as an artifact
      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheel
          path: wheelhouse/*.whl