name: Build and Install Python Wheel for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows manual trigger from GitHub UI


jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify Python 3.11

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'  # Install CMake via Chocolatey

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        python -m pip install wheel setuptools  # Install wheel and setuptools (necessary for building wheels)
        python -m pip install numpy==1.26.4  # Install numpy if your project requires it

    - name: Install OpenBLAS and LAPACK (via conda)
      run: |
        choco install miniconda3  # Install Miniconda for managing dependencies like OpenBLAS, LAPACK
        call C:\tools\Miniconda3\Scripts\activate.bat  # Activate Miniconda
        conda install -y -c conda-forge libblas liblapack openblas  # Install LAPACK, BLAS via conda

    - name: Set up C++ build tools (MSVC)
      run: |
        choco install visualcpp-build-tools  # Install the Visual C++ build tools via Chocolatey
        echo "::add-path::C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin" >> $GITHUB_PATH  # Add MSBuild to PATH

    - name: Install the package
      run: |
        pip install .  # Install the package using pip (this is equivalent to 'python setup.py install')
        # OR: python ./setup.py install  # Uncomment this line if you want to use 'setup.py install' instead of pip

    - name: Upload wheel artifact (optional)
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl  # Upload the built wheel to GitHub Actions artifacts
